version: '3.7'

services:
  meme-bot:
    build: bot
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - ./bot:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  web:
    image: nginx:1.21.4-alpine
    restart: unless-stopped
    ports:
      - '${PORT}:80'
    depends_on:
      - meme-bot
    volumes:
      - ./web/dist/meme-bot-web:/usr/share/nginx/html
      - ./bot/src/config.json:/usr/share/nginx/html/assets/config.json:ro
      - ./bot/images:/usr/share/nginx/html/assets/images:ro
