version: '3.7'

services:
  meme-bot:
    build: bot
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - ./bot:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
