version: '3.7'

services:
  your-bot:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
